### ISSUE TITLE
Location services not being approved on Android

### ISSUE THREAD

**Issue by XOneTrick** [jose-vs/Loocate#6]
So ive been on this way too long now and im sorry, i need to ask for help.

https://github.com/react-native-maps/react-native-maps/issues/2747

This link seems to show the exact same issue as i am facing right now with the location services not working properly on android. 

We have 'expo-location' whihc should automatly add the correct permssions into the 'androidmanifest.xml'. This is currently a file unaccessible in our project as we are running a managed project on expo hence why it is automattically added when using packing 'expo-location'

I have been trying to see if i need to use 'ACCESS_FINE_LOCATION' permission instead but am struggling to understand how to add it without ejecting the project.

We should be using 'const { status } = await Permission.askAsync(Permission.LOCATION)' to ask for location services but im struggling to understand where and when i should be asking for this.

-----

Below is a comment from the above link, if anyone is able to help me out on implementing this in the mapView that would be great, im struggling trying to see how it would fit in and where

-----

I faced a similar issue. Showing user location works out-of-the-box on iOS but not on Android.
I found a workaround to ask for permissions using PermissionsAndroid module on map ready

<Map
  onMapReady={() => {
    PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
    ).then(granted => {
      alert(granted) // just to ensure that permissions were granted
    });
  }}
/>
Also don't forget to include permissions in AndroidManifest.xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

Ensure that GPS is enabled on your device/emulator. This solution shows the current location with a short delay.

If you want to show a button that you called "re-centering" you should use prop showUserLocationButton. I also faced issue with that, the button was not showing. The workaround was to force map re-render - check this related issue #2010 (comment)

**Comment by David10088** [comment]
issue resolved, location works
